name: design
favicon: null
layout_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#af8965'
    - '#8d9d90'
    - '#8b664b'
    - '#679092'
    - '#488391'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
