name: design
favicon: null
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#29383b'
    - '#e9484d'
    - '#3cd5d2'
    - '#939b9d'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
