name: design
favicon: null
layout_spectrum: 0.99181
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#666666'
    - '#989898'
    - '#000000'
    - '#db1b22'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
