name: design
favicon: null
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ececee'
    - '#030207'
    - '#80775a'
    - '#f59ea7'
    - '#9e202d'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
