name: design
favicon: null
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#242424'
    - '#c0c0c0'
    - '#ed624b'
    - '#8a8a8a'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
